version: '3'
services: 
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postpas
    webapp:
        depends_on: [db]
        image: duccl/flask-to-do-image:v1
        restart: always
        environment:
            DATABASE_URL: postgresql+psycopg2://postgres:postpas@db:5432/postgres
            FLASK_HOST: 0.0.0.0
            PRODUCTION: 1
            TASK_API_VERSION: v1
        ports: 
        - "5000:5000"